Stance.create!([
  {description: "50/50, feet parallel with heels and toes together", image_file_name: "heisoku.JPG", image_content_type: "image/jpeg", image_file_size: 114099, image_updated_at: "2016-04-15 09:34:53", japanese_name: "Heisoku Dachi", english_name: "Closed-toe stance"},
  {description: "50/50, heels together, each foot at 45 degs", image_file_name: "musubi.JPG", image_content_type: "image/jpeg", image_file_size: 107624, image_updated_at: "2016-04-15 09:35:54", japanese_name: "Musubi Dachi", english_name: "Open-toe stance"},
  {description: "50/50, feet pointing straight ahead, shoulder width apart.", image_file_name: "heiko.JPG", image_content_type: "image/jpeg", image_file_size: 87150, image_updated_at: "2016-04-15 09:37:49", japanese_name: "Heiko Dachi", english_name: "Parallel Stance"},
  {description: "50/50, feet are parallel, back straight.", image_file_name: "kiba.JPG", image_content_type: "image/jpeg", image_file_size: 92489, image_updated_at: "2016-04-15 09:41:42", japanese_name: "Kiba Dachi", english_name: "Straddle Stance (horse riding stance)"},
  {description: "50/50, heels out and toes pointed in.", image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, japanese_name: "Uchi Hachiji Dachi", english_name: "Inverted open leg stance"},
  {description: "Shoulder width apart, toes about 30deg angle, 50/50.", image_file_name: "fudp.JPG", image_content_type: "image/jpeg", image_file_size: 106806, image_updated_at: "2016-04-15 09:43:46", japanese_name: "Fudo Dachi", english_name: "Normal Stance"},
  {description: "50/50, similar to kiba dachi but feet turned out.", image_file_name: "shiko.JPG", image_content_type: "image/jpeg", image_file_size: 100421, image_updated_at: "2016-04-15 09:44:26", japanese_name: "Shiko Dachie", english_name: "Sumo Stance"},
  {description: "Front foot staggered in front of back, heels twisted out, knees slightly bent, 50/50.", image_file_name: "sanchin.JPG", image_content_type: "image/jpeg", image_file_size: 99044, image_updated_at: "2016-04-15 09:45:28", japanese_name: "Sanchin Dachi", english_name: "Three-point Stance"},
  {description: "70 front, 30 back, shoulder width apart, front leg, knee bent over ankle, back leg straight, foot at 45deg, length about 2 shoulder widths.", image_file_name: "zenkutsu1.JPG", image_content_type: "image/jpeg", image_file_size: 185695, image_updated_at: "2016-04-15 09:52:17", japanese_name: "Zenkutsu Dachi", english_name: "Front learning Stance"},
  {description: "70 back, 30 front, feet shoulder width apart, not directly behind each other, hips low, sitting on back leg, heel front leg up, ody twisted so to not expose torso, hands in basic fighting stance.", image_file_name: "kokutsu1.JPG", image_content_type: "image/jpeg", image_file_size: 168590, image_updated_at: "2016-04-15 09:52:39", japanese_name: "Kokutsu Dachi", english_name: "Back Leaning Stance"}
])
