Stance.create!([
  {description: "50/50, feet parallel with heels and toes together", image_file_name: "heisoku.JPG", image_content_type: "image/jpeg", image_file_size: 114099, image_updated_at: "2016-04-15 09:34:53", japanese_name: "Heisoku Dachi", english_name: "Closed-toe stance"},
  {description: "50/50, heels together, each foot at 45 degs", image_file_name: "musubi.JPG", image_content_type: "image/jpeg", image_file_size: 107624, image_updated_at: "2016-04-15 09:35:54", japanese_name: "Musubi Dachi", english_name: "Open-toe stance"},
  {description: "50/50, feet pointing straight ahead, shoulder width apart.", image_file_name: "heiko.JPG", image_content_type: "image/jpeg", image_file_size: 87150, image_updated_at: "2016-04-15 09:37:49", japanese_name: "Heiko Dachi", english_name: "Parallel Stance"},
  {description: "50/50, feet are parallel, back straight.", image_file_name: "kiba.JPG", image_content_type: "image/jpeg", image_file_size: 92489, image_updated_at: "2016-04-15 09:41:42", japanese_name: "Kiba Dachi", english_name: "Straddle Stance (horse riding stance)"},
  {description: "Shoulder width apart, toes about 30deg angle, 50/50.", image_file_name: "fudp.JPG", image_content_type: "image/jpeg", image_file_size: 106806, image_updated_at: "2016-04-15 09:43:46", japanese_name: "Fudo Dachi", english_name: "Normal Stance"},
  {description: "50/50, similar to kiba dachi but feet turned out.", image_file_name: "shiko.JPG", image_content_type: "image/jpeg", image_file_size: 100421, image_updated_at: "2016-04-15 09:44:26", japanese_name: "Shiko Dachie", english_name: "Sumo Stance"},
  {description: "Front foot staggered in front of back, heels twisted out, knees slightly bent, 50/50.", image_file_name: "sanchin.JPG", image_content_type: "image/jpeg", image_file_size: 99044, image_updated_at: "2016-04-15 09:45:28", japanese_name: "Sanchin Dachi", english_name: "Three-point Stance"},
  {description: "70 front, 30 back, shoulder width apart, front leg, knee bent over ankle, back leg straight, foot at 45deg, length about 2 shoulder widths.", image_file_name: "zenkutsu1.JPG", image_content_type: "image/jpeg", image_file_size: 185695, image_updated_at: "2016-04-15 09:52:17", japanese_name: "Zenkutsu Dachi", english_name: "Front learning Stance"},
  {description: "70 back, 30 front, feet shoulder width apart, not directly behind each other, hips low, sitting on back leg, heel front leg up, ody twisted so to not expose torso, hands in basic fighting stance.", image_file_name: "kokutsu1.JPG", image_content_type: "image/jpeg", image_file_size: 168590, image_updated_at: "2016-04-15 09:52:39", japanese_name: "Kokutsu Dachi", english_name: "Back Leaning Stance"},
  {description: "50/50, heels out and toes pointed in.", image_file_name: "uchi_hachiji.JPG", image_content_type: "image/jpeg", image_file_size: 136203, image_updated_at: "2016-04-16 04:52:49", japanese_name: "Uchi Hachiji Dachi", english_name: "Inverted open leg stance"},
  {description: "Advanced stance, 100 back leg, knee slightly bent, instep of front foot hooked behind knee of back leg, execute a quick joint or side kick.", image_file_name: "sagi_ashi.JPG", image_content_type: "image/jpeg", image_file_size: 170501, image_updated_at: "2016-04-16 04:55:01", japanese_name: "Sahi Ashi Dachi", english_name: "One Legged Stance"},
  {description: "Both feet in one line, most of weight on knee, on ball off foot of back leg,", image_file_name: "kata_h.JPG", image_content_type: "image/jpeg", image_file_size: 121623, image_updated_at: "2016-04-16 04:56:01", japanese_name: "Kata Hiza Dachi", english_name: "One Knee Stance"},
  {description: "Like back leaning stance, most of weight on back leg, 90. Front foot pulled toward back foot, one foot length away, both knees bent, hips pushed back.", image_file_name: "nekoyshi.JPG", image_content_type: "image/jpeg", image_file_size: 158430, image_updated_at: "2016-04-16 04:57:32", japanese_name: "Nekoashi Dachi", english_name: "Cat Stance"},
  {description: "Similar to Sagi Ashi Dachi. Foot of raised left kept at side of knee. Support leg is almost straight, 100%.", image_file_name: "tsuruashi2.JPG", image_content_type: "image/jpeg", image_file_size: 116239, image_updated_at: "2016-04-16 04:58:57", japanese_name: "Tsuruashi Dachi", english_name: "Crane Stance"},
  {description: "Right knee slightly bent, left foot has stepped behind, heel up, on ball of foot. For quick tranistions.", image_file_name: "kake.JPG", image_content_type: "image/jpeg", image_file_size: 79568, image_updated_at: "2016-04-16 05:00:41", japanese_name: "Kake Dachi", english_name: "Hooked Stance"},
  {description: "Like parallel stance, except one foot is in front of other. 50/50.", image_file_name: "kuzure.JPG", image_content_type: "image/jpeg", image_file_size: 144563, image_updated_at: "2016-04-16 05:05:26", japanese_name: "Kuzure Heiko Dachi", english_name: "Staggered Parallel Stance"}
])
